version: '2'
volumes:
  schd-conf:
    driver: rancher-nfs
    # per_container: true
  data-0:
    driver: rancher-nfs
    # per_container: true
services:
  rancher-cattle-metadata:
    image: webcenter/rancher-cattle-metadata:1.0.1
    network_mode: none
    volumes:
    - schd-conf:/opt/scheduler
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  minio-server:
    image: webcenter/alpine-minio:2017-03-16_4
    environment:
      CONFD_BACKEND: env
      CONFD_NODES: ''
      CONFD_PREFIX_KEY: /minio
      MINIO_CONFIG_minio.access.key: ${rancher_access_key}
      MINIO_CONFIG_minio.secret.key: ${rancher_secret_key}
      MINIO_DISKS_0: disk0
    volumes:
    - schd-conf:/opt/scheduler
    - data-0:/data/disk0
    tty: true
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.sidekicks: rancher-cattle-metadata
      io.rancher.container.hostname_override: container_name
  mc:
    image: supersoftware/bop:mc
    environment:
      ALIAS: ${mc_alias}
      MINIO_URL: http://minio-server:9000
      RANCHER_ACCESS_KEY: ${rancher_access_key}
      RANCHER_SECRET_KEY: ${rancher_secret_key}
      API_SIGNATURE: ${mc_api_signature}
    stdin_open: true
    tty: true
    links:
    - ${mini_service_name}:minio-server
    command:
    - /bin/sh
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
