version: '2'
.catalog:
  name: gateway
  description: |
    BOP Gateway Stack Template
  version: 0.1.0-beta-rancher1
  category: Applications
  maintainer: "Kazuhito Yamazawa <yamazawa@supersoftware.co.jp>"
  minimum_rancher_version: v1.5.3
  uuid: gateway-0
  questions:
  - variable: "pg_database"
    description: ""
    label: "Postgres Database"
    required: true
    default: "kong"
    type: "string"
  - variable: "pg_user"
    description: ""
    label: "Postgres User"
    required: true
    default: "kong"
    type: "string"
  - variable: "pg_password"
    description: ""
    label: "Postgres Password"
    required: true
    default: ""
    type: "password"
services:
  kong-dashboard:
    start_on_create: true
  postgres:
    scale: 1
    start_on_create: true
  kong:
    start_on_create: true
    health_check:
      response_timeout: 5000
      healthy_threshold: 2
      port: 8001
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 5000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
